headers = {
    "accept": "*/*",
    "accept-language": "ru-UA,ru;q=0.9,en-US;q=0.8,en;q=0.7,uk-UA;q=0.6,uk;q=0.5",
    "cache-control": "no-cache",
    "content-type": "application/json",
    "origin": "https://ago-wallet.hexacore.io",
    "pragma": "no-cache",
    "priority": "u=1, i",
    "referer": "https://ago-wallet.hexacore.io/",
    "sec-ch-ua-mobile": "?1",
    "sec-ch-ua-platform": '"Android"',
    "sec-fetch-dest": "empty",
    "sec-fetch-mode": "cors",
    "sec-fetch-site": "same-site",
    'x-requested-with': 'org.telegram.messenger',
}
