class WebappURLs:
    BASE_URL = 'https://ago-api.hexacore.io/api/'
    APP_AUTH = f'{BASE_URL}app-auth'
    USER_EXISTS = f'{BASE_URL}user-exists'
    BALANCE = f'{BASE_URL}balance'
    LEVEL = f'{BASE_URL}level'
    UPGRADE_LEVEL = f'{BASE_URL}upgrade-level'
    DAILY_REWARD = f'{BASE_URL}daily-reward'
    DAILY_CHECKIN = f'{BASE_URL}daily-checkin'
    CREATE_USER = f'{BASE_URL}create-user'
    AVAILABLE_TAPS = f'{BASE_URL}available-taps'
    GET_TAP_PASSES = f'{BASE_URL}get-tap-passes'
    BUY_TAP_PASSES = f'{BASE_URL}buy-tap-passes'
    MINING_COMPLETE = f'{BASE_URL}mining-complete'
    MISSIONS = f'{BASE_URL}missions'
    MISSION_COMPLETE = f'{BASE_URL}mission-complete'
    IN_GAME_REWARD_AVAILABLE = f'{BASE_URL}in-game-reward-available'
    IN_GAME_REWARD = f'{BASE_URL}in-game-reward'

